source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

gem 'twitter'
gem 'oauth'

gem 'sidekiq'
gem 'redis'

group :test do
  gem 'faker'
  gem 'rspec'
end